kind: pipeline
type: kubernetes
name: default

steps:
  - name: "Build and Publish"
    image: banzaicloud/drone-kaniko:0.5.1
    settings:
      registry: registry.tomgoring.co.uk
      repo: tomgo/client
      auto_tag: true
      cache: true
      skip_tls_verify: false
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push

  - name: "Test Build"
    image: banzaicloud/drone-kaniko:0.5.1
    when:
      branch:
        - devel
      event:
        - push

  - name: "Test PR"
    image: banzaicloud/drone-kaniko:0.5.1
    when:
      branch:
        - master
      event:
        - pull_request

  - name: "Deploy"
    image: sinlead/drone-kubectl
    settings:
      kubernetes_token:
        from_secret: kube_svacct_token
    commands:
      - kubectl delete pods -l app=tgcu
    when:
      branch:
        - master
      event:
        - push

image_pull_secrets:
  - registry-auth-json
